### ISSUE TITLE
Cloud saves tracking

### ISSUE THREAD

**Issue by belohlavek** [decentraland/builder#584]
- [ ] Track QuotaExceeded
- [ ] Track handled errors
- [ ] Track sign in
- [ ] Review old events (use auth0 id)

**Comment by belohlavek** [comment]
- cambiar los identify cuando te conectas con la wallet para que agreguen el eth_address como trait en vez de como user_id
• agregar identifies after login con el user_id de auth0
• trackear boton de login y logout
• trackear modal de que te quedaste sin espacio
