### ISSUE TITLE
Client side todo list

### ISSUE THREAD

**Issue by menduz** [decentraland/builder#82]
- [x] Use `metricsUpdate` event, now added to the client (decentraland/client#239d6733)
- [x] Fix camera weird rotation on change to FPS mode (decentraland/client#2b1c1c92)
- [x] Fix dark checkerboard material in FPS mode (decentraland/client#2b1c1c92)
- [x] Entities are no longer clickable after comming back from FPS mode (#c727bea5)
- [x] Fix floor color in NON editor mode (#f12d551d)
- [x] Make a smoother camera (#f12d551d)

**Comment by belohlavek** [comment]
Mmmh you should track these here instead:
https://github.com/decentraland/client/projects/7

We do keep an eye on those
